version: '3.9'

services:
  postgres:
    image: 'postgres:13.2-alpine'
    environment:
      POSTGRES_PASSWORD: 'dev'
      POSTGRES_USER: 'dev'
      POSTGRES_DB: 'dev'
    ports:
      - '5432:5432'
